### PR TITLE
Disabled resizing

### PR DESCRIPTION
**Pull request by Tetrapak0**

### CODE REVIEW

**Comment by Tetrapak0** [comment]
I have re created the pr with all changes.

**Comment by Tetrapak0** [comment]
Please review this PR. I would like to delete my fork.

**Comment by Tetrapak0** [comment]
@Mr-Technician

**Comment by Mr-Technician** [comment]
@Tetrapak0 Hey sorry for being unresponsive, I will try to look tonight after work!

**Pull request closed without merging**
